%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera.fx: 809.423284048306
Camera.fy: 808.183453260988
Camera.cx: 779.603261139102
Camera.cy: 600.767993727494

Camera.k1: -0.0501592174073641
Camera.k2: 0.105531361259854
Camera.k3: -0.0518827035319686
Camera.p1: 1.509557786743519e-04
Camera.p2: -7.312116719342477e-05

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 805.458427142002
Camera2.fy: 804.166682377088
Camera2.cx: 780.385886608082
Camera2.cy: 601.102365557975

Camera2.k1: -0.0533394483291042
Camera2.k2: 0.111560864880882
Camera2.k3: -0.0551281609057820
Camera2.p1: 1.86032836987892e-05
Camera2.p2: -0.000303642532971288

# Transformation matrix from right camera to left camera
Tlr: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [1.0000, -0.0081, 0.0034, -0.1996194,
         0.0081, 1.0000, -0.0042, 0.0010670,
         -0.0034, 0.0042, 1.0000, -0.0007914,
         0.0, 0.0, 0.0, 1.0]

# Configurações de imagem
Camera.width: 1600
Camera.height: 1200
Camera.fps: 50
Camera.RGB: 1

# Baseline * fx (0.19984 * 404.3704 ≈ 80.8)
Camera.bf: 80.0

# Limiares de profundidade
ThDepth: 60.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1200
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0