%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera.fx: 404.824914642116
Camera.fy: 404.198455109877
Camera.cx: 390.095896291091
Camera.cy: 300.660229377819

Camera.k1: -0.0477741948433809
Camera.k2: 0.102372392208401
Camera.k3: -0.0506870223053082
Camera.p1: 0.000153517027498703
Camera.p2: -3.94653647321177e-05

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 402.848563322428
Camera2.fy: 402.187949112860
Camera2.cx: 390.452987641561
Camera2.cy: 300.830353671574

Camera2.k1: -0.0512755674190962
Camera2.k2: 0.109278668308137
Camera2.k3: -0.0544562081541737
Camera2.p1: 3.05814571400832e-05
Camera2.p2: -0.000300136855492693

# Transformation matrix from right camera to left camera
Tlr: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [1.0000, -0.0081, 0.0033, -0.1996375,
         0.0081, 1.0000, -0.0041, 0.0010695,
         -0.0033, 0.0041, 1.0000, -0.0007780,
         0.0, 0.0, 0.0, 1.0]

# Configurações de imagem
Camera.width: 800
Camera.height: 600
Camera.fps: 50
Camera.RGB: 1

# Baseline * fx (0.19984 * 404.3704 ≈ 80.8)
Camera.bf: 80.0

# Limiares de profundidade
ThDepth: 60.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1200
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0	q