%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 404.3704
Camera1.fy: 404.3170
Camera1.cx: 390.3187
Camera1.cy: 298.0105

Camera1.k1: -0.0363
Camera1.k2: 0.0785
Camera1.k3: -0.0369
Camera1.p1: -0.00059037
Camera1.p2: 0.00000079374

# Camera resolution
Camera.width: 800
Camera.height: 600

Camera.fps: 40

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1


# Transformation from camera to IMU
IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.9999942541521951, 0.003305880986961045, 0.0007502089673450355, -0.07457090702528762,
    -0.003301174755933806, 0.9999753923120803, -0.0061900739520239206, -0.0074128162865161416,
    -0.0007706541542227714, 0.006187561813896418, 0.9999805598965279, -0.038081849071972415,
    0.0, 0.0, 0.0, 1.0]

# IMU noise
IMU.NoiseGyro: 9.99644870663471e-05
IMU.NoiseAcc: 0.0017554276547521732
IMU.GyroWalk: 5.291169461542846e-07
IMU.AccWalk: 3.839650514071629e-05
IMU.Frequency: 250.0


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1500
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0
