%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 404.824914642116
Camera1.fy: 404.198455109877
Camera1.cx: 390.095896291091
Camera1.cy: 300.660229377819

Camera1.k1: -0.0477741948433809
Camera1.k2: 0.102372392208401
Camera1.k3: -0.0506870223053082
Camera1.p1: 0.000153517027498703
Camera1.p2: -3.94653647321177e-05


# Camera resolution
Camera.width: 800
Camera.height: 600

Camera.fps: 40

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

         # Transformation from camera to IMU
IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.9999942541521951, 0.003305880986961045, 0.0007502089673450355, -0.07457090702528762,
    -0.003301174755933806, 0.9999753923120803, -0.0061900739520239206, -0.0074128162865161416,
    -0.0007706541542227714, 0.006187561813896418, 0.9999805598965279, -0.038081849071972415,
    0.0, 0.0, 0.0, 1.0]

# IMU noise
IMU.NoiseGyro: 0.00010030383677353103 
IMU.NoiseAcc: 0.0017862283519383298 
IMU.GyroWalk: 5.005899751017297e-07 
IMU.AccWalk: 3.745251231312492e-05 
IMU.Frequency: 250.0


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1500
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0