%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"


#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# --- Câmera 1 (Esquerda) ---
# Extraído de: stereoParams.CameraParameters1
# Erro de Reprojeção Individual: 0.1022
Camera1.fx: 405.7146
Camera1.fy: 405.1880
Camera1.cx: 389.0527
Camera1.cy: 300.0990
# Coeficientes de distorção Radial (k1, k2, k3) e Tangencial (p1, p2)
Camera1.k1: -0.0415
Camera1.k2: 0.0878
Camera1.k3: -0.0411
Camera1.p1: -0.000065485 # -6.5485e-05
Camera1.p2: -0.0010

# --- Câmera 2 (Direita) ---
# Extraído de: stereoParams.CameraParameters2
# Erro de Reprojeção Individual: 0.0992
Camera2.fx: 403.9694
Camera2.fy: 403.5188
Camera2.cx: 389.2633
Camera2.cy: 300.4624
# Coeficientes de distorção Radial (k1, k2, k3) e Tangencial (p1, p2)
Camera2.k1: -0.0491
Camera2.k2: 0.1086
Camera2.k3: -0.0557
Camera2.p1: -0.000032118 # -3.2118e-04
Camera2.p2: -0.0013

# --- Dimensões da Imagem ---
# Extraído de ambos os parâmetros da câmera
Camera.width: 800
Camera.height: 600

# --- Configurações Gerais ---
Camera.fps: 30 # Ajuste para o FPS do seu vídeo/câmera
Camera.RGB: 1   # 1 para RGB, 0 para BGR

# --- Parâmetros Estéreo ---
# O baseline*fx. Este valor pode precisar de ajuste fino.
Stereo.bf: 40.0 

# Limiar de profundidade para considerar pontos próximos/distantes.
Stereo.ThDepth: 40.0

# --- Matriz de Transformação Estéreo (Extrínsecos) ---
# Extraído de: stereoParams.RotationOfCamera2 e stereoParams.TranslationOfCamera2
# Nota: A translação foi dividida por 1000 para converter de mm (do MATLAB) para m.
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 1.0000, -0.0084, 0.0043, -0.1997409,
     0.0085, 0.9999, -0.0059, 0.0010668,
     -0.0043, 0.0059, 1.0000, -0.0004199,
     0.0, 0.0, 0.0, 1.0 ]
#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500

# ORB Extractor: Scale factor between levels in the scale pyramid   
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid  
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast     
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0
