%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"


#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 417.0354
Camera1.fy: 373.7859
Camera1.cx: 404.6803
Camera1.cy: 301.8623

Camera1.k1: -0.2024
Camera1.k2: 0.0820
Camera1.k3: -0.0144
Camera1.p1: -0.00045161
Camera1.p2: 0.00022801

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 417.2918
Camera2.fy: 374.0319
Camera2.cx: 403.2971
Camera2.cy: 302.0898

Camera2.k1: -0.2038
Camera2.k2: 0.0843
Camera2.k3: -0.0153
Camera2.p1: -0.00016415
Camera2.p2: -0.000054179

Camera.width: 800
Camera.height: 600

Camera.fps: 60
Camera.RGB: 1

Stereo.ThDepth: 60.0

Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.9997, 0.0229, -0.0030, -0.2002738,
         -0.0229, 0.9997, 0.0035, 0.0013542,
         0.0029, -0.0036, 1.0000, -0.0001777,
         0, 0, 0, 1]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

ORBextractor.nFeatures: 1500
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0