%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera.fx: 809.423284048306
Camera.fy: 808.183453260988
Camera.cx: 779.603261139102
Camera.cy: 600.767993727494

Camera.k1: -0.0501592174073641
Camera.k2: 0.105531361259854
Camera.k3: -0.0518827035319686
Camera.p1: 1.509557786743519e-04
Camera.p2: -7.312116719342477e-05

# Configurações de imagem
Camera.width: 1600
Camera.height: 1200
Camera.fps: 50
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# IMU Parameters (com transformação corrigida)
#--------------------------------------------------------------------------------------------
# Transformation from body-frame (IMU) to left camera
Tbc: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.9999942541521951, 0.003305880986961045, 0.0007502089673450355, -0.07586462921941707,
         -0.003301174755933806, 0.9999753923120803, -0.0061900739520239206, -0.0074128162865161416,
         -0.0007706541542227714, 0.006187561813896418, 0.9999805598965279, -0.038081849071972415,
         0.0, 0.0, 0.0, 1.0]

# IMU noise
IMU.NoiseGyro: 0.00010030383677353103 
IMU.NoiseAcc: 0.0017862283519383298 
IMU.GyroWalk: 5.005899751017297e-07 
IMU.AccWalk: 3.745251231312492e-05 
IMU.Frequency: 250

#--------------------------------------------------------------------------------------------
# ORB Parameters (otimizado para monocular)
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1500  # Aumentado para monocular
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5  # Melhor para visualização monocular
Viewer.ViewpointF: 500.0