%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 809.5590
Camera1.fy: 809.4373
Camera1.cx: 779.8459
Camera1.cy: 595.5954

Camera1.k1: -0.0395
Camera1.k2: 0.0827
Camera1.p1: -0.0006
Camera1.p2: 0.0001

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 805.3451
Camera2.fy: 805.2451
Camera2.cx: 781.8989
Camera2.cy: 598.6680

Camera2.k1: -0.0466
Camera2.k2: 0.1005
Camera2.p1: -0.0005
Camera2.p2: -0.0001

# Camera resolution
Camera.width: 1600
Camera.height: 1200

Camera.fps: 40

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Baseline times focal length (bf = baseline * fx)
Camera.bf: 48.0  # Ajuste este valor com base na baseline do seu sistema estéreo

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Stereo.ThDepth: 60.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.9999, 0.0098, -0.0046, -0.1998684,
         -0.0098, 0.9999, 0.0043, 0.0007489,
         0.0047, -0.0043, 1.0000, -0.0011766,
         0.0, 0.0, 0.0, 1.0]
         # Transformation from camera to IMU
IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.9999942541521951, 0.003305880986961045, 0.0007502089673450355, -0.07457090702528762,
    -0.003301174755933806, 0.9999753923120803, -0.0061900739520239206, -0.0074128162865161416,
    -0.0007706541542227714, 0.006187561813896418, 0.9999805598965279, -0.038081849071972415,
    0.0, 0.0, 0.0, 1.0]

# IMU noise
IMU.NoiseGyro: 9.99644870663471e-05
IMU.NoiseAcc: 0.0017554276547521732
IMU.GyroWalk: 5.291169461542846e-07
IMU.AccWalk: 3.839650514071629e-05
IMU.Frequency: 250.0


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1500
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0
